# Generated by Django 6.0 on 2026-09-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Institución/UGEL')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('eslogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eslogan')),
                ('quienes_somos', models.TextField(blank=True, null=True, verbose_name='Quiénes Somos')),
                ('mision', models.TextField(blank=True, null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Visión')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/ugel/', verbose_name='Logo Institucional')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media/ugel/', verbose_name='Banner Institucional')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
            ],
            options={
                'verbose_name': 'UGEL',
                'verbose_name_plural': 'Datos de UGEL',
                'db_table': 'ugel',
            },
        ),
    ]
