# Generated by Django 6.0 on 2026-09-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Distrito')),
                ('provincia', models.CharField(default='Yungay', max_length=100, verbose_name='Provincia')),
                ('departamento', models.CharField(default='Ancash', max_length=100, verbose_name='Departamento')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'distrito',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_falta', models.CharField(max_length=100, verbose_name='Tipo de Falta')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Falta')),
                ('descuento_dias', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Días de Descuento')),
                ('justificable', models.BooleanField(default=True, verbose_name='¿Es Justificable?')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
                'db_table': 'falta',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nivel Educativo')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'db_table': 'nivel',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tardanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_inicio', models.IntegerField(help_text='Ej: De 1 a 15 min', verbose_name='Minutos Inicio')),
                ('minutos_fin', models.IntegerField(help_text='Ej: De 16 a 30 min', verbose_name='Minutos Fin')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Sanción / Descuento (%)')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Tolerancia / Tipo Tardanza')),
            ],
            options={
                'verbose_name': 'Tardanza',
                'verbose_name_plural': 'Tardanzas',
                'db_table': 'tardanza',
                'ordering': ['minutos_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Turno')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turno',
                'ordering': ['nombre'],
            },
        ),
    ]
