# Generated by Django 6.0 on 2026-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_cargo_distrito_falta_nivel_tardanza_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='distrito',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Distrito'),
        ),
    ]
