# Generated by Django 6.0 on 2026-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_distrito_options_remove_distrito_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='falta',
            options={'verbose_name': 'Falta', 'verbose_name_plural': 'Faltas'},
        ),
        migrations.AlterModelOptions(
            name='tardanza',
            options={'verbose_name': 'Tardanza', 'verbose_name_plural': 'Tardanzas'},
        ),
        migrations.RemoveField(
            model_name='falta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='falta',
            name='descuento_dias',
        ),
        migrations.RemoveField(
            model_name='tardanza',
            name='descuento_porcentaje',
        ),
        migrations.RemoveField(
            model_name='tardanza',
            name='minutos_fin',
        ),
        migrations.RemoveField(
            model_name='tardanza',
            name='minutos_inicio',
        ),
        migrations.AddField(
            model_name='falta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='falta',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tardanza',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tardanza',
            name='justificable',
            field=models.BooleanField(default=False, verbose_name='¿Es Justificable?'),
        ),
        migrations.AddField(
            model_name='tardanza',
            name='tipo_tardanza',
            field=models.CharField(default='Tardanza General', max_length=100, unique=True, verbose_name='Tipo de Tardanza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='falta',
            name='justificable',
            field=models.BooleanField(default=False, verbose_name='¿Es Justificable?'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='tipo_falta',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo de Falta'),
        ),
        migrations.AlterField(
            model_name='tardanza',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
