# Generated by Django 6.0 on 2026-10-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_falta_options_alter_tardanza_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modular', models.CharField(max_length=12, unique=True, verbose_name='Código Modular')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Institución')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('tolerancia', models.IntegerField(default=15, help_text='Tolerancia en minutos', verbose_name='Tolerancia (Min)')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones', to='asistencia.distrito', verbose_name='Distrito')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones', to='asistencia.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'instituciones',
                'ordering': ['-id'],
            },
        ),
    ]
