# Generated by Django 6.0 on 2026-10-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_modular', models.CharField(max_length=12, unique=True, verbose_name='Código Modular')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('huella_indice', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Huella Índice')),
                ('huella_pulgar', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Huella Pulgar')),
                ('h_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('h_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('condicion', models.BooleanField(default=True, verbose_name='Estado/Condición')),
                ('dia_descanso', models.CharField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=15, null=True, verbose_name='Día de Descanso')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.cargo', verbose_name='Cargo')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.distrito', verbose_name='Distrito')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.institucion', verbose_name='Institución')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.nivel', verbose_name='Nivel Educativo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['-id'],
            },
        ),
    ]
