# Generated by Django 6.0 on 2026-10-03 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_dispositivo', models.CharField(max_length=100, unique=True, verbose_name='Serie del Dispositivo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='asistencia.institucion', verbose_name='Institución Educativa')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['-id'],
            },
        ),
    ]
